name: build-and-deploy
on:
  schedule:
    - cron: "*/30 * * * *"   # 30분마다 자동 실행
  workflow_dispatch: {}      # 수동 실행 버튼
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build static page
        run: python scripts/build.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: site }
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
